# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.3.0"
shadow = "9.3.1"
spotless = "8.2.0"
paperweight = "2.0.0-beta.19"
runPaper = "3.0.2"
resourceFactory = "1.3.1"

# project librairies
ntconfig = "0.0.1"
papermc = "1.21.11-R0.1-SNAPSHOT"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
shadowGradlePlugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
spotlessGradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

# project librairies
ntConfigCore = { module = "re.neotamia.config:ntconfig-core", version.ref = "ntconfig" }
ntConfigYaml = { module = "re.neotamia.config:ntconfig-yaml", version.ref = "ntconfig" }
papermcApi = { module = "io.papermc.paper:paper-api", version.ref = "papermc" }

[bundles]
ntConfig = ["ntConfigCore", "ntConfigYaml"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
resourceFactoryBukkit = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "resourceFactory" }
resourceFactoryPaper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactory" }
